user:
  info:
    service: mockUserInfoServiceImpl


encryption:
  aes:
    password:
      data: SIEGe0K4$XuceFy%
      jwt: Bten&eh9E5RrMQCE

upload:
  path: /Users/hexie/PycharmProjects/lipstick_spider/img/
